liquibase: Add `sourceRoot`
To fix the build issue that was introduced in f373abe60b11bf83c48a7fa84fc9f2c5c8d5151e
when the custom `unpackPhase` was removed without correctly validating the build,
which results in:
```
error: builder for '/nix/store/5qax6r6kxi4spn5bc7qjpgglxb9kvhxp-liquibase-4.29.2.drv' failed with exit code 1;
       last 3 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/v12lcsjxsq3n4lgi8za3k9mqc8pak59b-liquibase-4.29.2.tar.gz
       > unpacker produced multiple directories
       For full logs, run 'nix log /nix/store/5qax6r6kxi4spn5bc7qjpgglxb9kvhxp-liquibase-4.29.2.drv'.
```